### ISSUE TITLE
Index out of bounds on MIP problem

### ISSUE THREAD

**Issue by fwesselm** [ERGO-Code/HiGHS#1139]
Hello!

When trying to solve MIP problem 'rout' from MIPLIB3.0 on my 64-bit Windows machine, I get an index out-of-bounds error at the very end of the solution process in line 1313 of src/util/HighsSparseMatrix.cpp:

`result.index[result.count++] = iCol;`

I realized that the code switches to quad precision in one of the preceding iterations, and I think that this triggers the exception.

Specifically, starting in line 1318 of HighsSparseMatrix.cpp, there is an if-block which performs a std::move:

```
result.index = std::move(sum.nonzeroinds);
HighsInt result_num_nz = result.index.size();
result.count = result_num_nz;
```
I think that the code assumes that vector result.index has size 'num_col_', but this is not guaranteed after the move. I think one way to resolve this would be to resize the vector:

```
result.index = std::move(sum.nonzeroinds);
HighsInt result_num_nz = result.index.size();
result.count = result_num_nz;
// Size of moved vector may be too small; make sure it can store 'num_col_' elements.
result.index.resize(num_col_);
```

This fixed the out-of-bounds error on my side. I hope this is helpful for others who also run into this issue.

Regards,
Franz

**Comment by jajhall** [comment]
Interesting, I'll investigate

**Comment by jajhall** [comment]
I've not reproduced the behaviour with `route.mps`, but I'm working on Linux. However, your observation is correct. I've introduced the `result.index.resize(num_col_);` line, and an assert at the start of the method to check that `result.index.size()`is `num_col_`. I guess this hasn't caused problems before since the quad precision switch is rarely used, and any over-writing is usually into addresses that aren't used
