### ISSUE TITLE
assertion error

### ISSUE THREAD

**Issue by thrasibule** [ERGO-Code/HiGHS#1166]
I'm getting this segfault while running cvxpy test suite when using a highs based solver for mip programming: 

```/usr/include/c++/12.2.1/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = int; _Alloc = std::allocator<int>; reference = int&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.```

I've tracked it down to this line: https://github.com/ERGO-Code/HiGHS/blob/master/src/lp_data/HighsSolution.cpp#L1253

so what happens is that for a particular problem basic_index is empty, so &basic_index[0] is not defined. This happens because none of the row_status and col_status earlier are == HighsBasisStatus::kBasic. I'm not sure what's the right thing to do in this situation. Can we test for this case and error our cleanly or simplify the factor setup so as not to use those degenerate values?

**Comment by jajhall** [comment]
Thanks for flagging this up. Just a couple of days ago I changed the use of `&vector[0]` here (and in many other places) to `vector.data()`, as it was causing a segfault on Windows because `vector` has zero size. It's tolerated on Linux. The modified code is in the `latest` branch.

However, what puzzles me is why it's trying to call `accommodateAlienBasis` after solving a MIP, when there's no basis. I'll look into this tomorrow.

**Comment by jajhall** [comment]
So, I see why the MIP solver could be calling `accommodateAlienBasis` with an empty `basic_index` vector _during_ the MIP solve. The only "bug" was due to passing `&basic_index[0]` rather than `basic_index.data()`. As observed, this has very recently been changed and pushed to `latest`. This should soon migrate to a tagged HiGHS version.

**Comment by thrasibule** [comment]
Thank you very much for the quick reply and fix!
