### ISSUE TITLE
No presolve => assessLp(reduced_lp, options_) == HighsStatus::kOk' failed

### ISSUE THREAD

**Issue by Downsite** [ERGO-Code/HiGHS#1174]
If the following .mps file is run with the `--presolve "false"` flag, the following error occurs:

```
Running HiGHS 1.2.2 [date: 2023-02-20, git hash: 437c98b08]
Copyright (c) 2022 ERGO-Code under MIT licence terms
Number of BV entries in BOUNDS section is 35
MIP  out has 546 rows; 370 cols; 1302 nonzeros; 35 integer variables

Presolve is switched off

Solving MIP model with:
   546 rows
   370 cols (35 binary, 0 integer, 0 implied int., 335 continuous)
   1302 nonzeros

        Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work      
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

         0       0         0   0.00%   -2000           inf                  inf        0      0      0         0     0.0s
highs: /.../dep/HiGHS/src/lp_data/Highs.cpp:1014: HighsStatus Highs::run(): Assertion `assessLp(reduced_lp, options_) == HighsStatus::kOk' failed.

Aborted (core dumped)
```

The same behavior is present on master
```
Running HiGHS 1.5.0 [date: 2023-02-20, git hash: ce351010e]
Copyright (c) 2022 HiGHS under MIT licence terms
```

[out.mps.txt](https://github.com/ERGO-Code/HiGHS/files/10785591/out.mps.txt)
[out.lp.txt](https://github.com/ERGO-Code/HiGHS/files/10785598/out.lp.txt)

**Comment by Downsite** [comment]
Issues similar to #1080 and #1164 are the reason why I needed to set presolve to false.

**Comment by SanPen** [comment]
Hi, 

I've found this issue as well.

My experience is the following:

- I'm setting the model using the C++ interface.
- I replaced `assessLp(reduced_lp, options_) == HighsStatus::kOk` by:
```
if(assessLp(reduced_lp, options_) != HighsStatus::kOk){
    writeModel("assessLp_exception.mps");
    throw std::runtime_error("assessLp failed :(");
}
```
- As you can see, I save the model for further inspection [assessLp_exception.mps](https://github.com/ERGO-Code/HiGHS/files/10861929/assessLp_exception.mps.txt)

- When I run this model on the console it works surprisingly.

**Comment by jajhall** [comment]
> * When I run this model on the console it works surprisingly.
>       (I'm on version 1.5.1)

After the call to `assessLp`, the small values have been removed, so won't be in `assessLp_exception.mps`, and even if they were, there's another `assessLp` when reading in a file to ensure that small values from the user are cleaned out. Obviously there's no assert on this happening.

**Comment by SanPen** [comment]
So are the issues due to small values?

**Comment by jajhall** [comment]
The original LP/MIP may well not have small entries, and any small entries are filtered out by HiGHS when the problem is passed to it. What's happening internally, is that LP/MIP presolve _creates_ small values due to scaling and subtraction. 

Your example @SanPen is useful, as it's an LP, so the small values are created by the LP presolve, which reduces the search space for what's creating them. As has been observed elsewhere (#1184), if HiGHS is built as release, then the call to assessLp in the assert is skipped, so the LP would be solved with small nonzeros in the matrix. 

The small nonzeros may not be a problem for the simplex solver: I just want to get a handle on what sort of values we're talking about, and what's the consequence of treating them as zero.
