### ISSUE TITLE
Getting number of LP iterations when solving a MIP problem

### ISSUE THREAD

**Issue by mapgccv** [ERGO-Code/HiGHS#1178]
I'm not sure if it's an issue or if it is a design decision:
when solving a MIP problem, the attribute `simplex_iteration_counts `does not seem to reflect the value printed in the log (which is stored in `HighsMipSolverData::total_lp_iterations`).

**Comment by jajhall** [comment]
We didn't think that it was worth propagating the total number of simplex iterations when solving a MIP to `HighsInfo`. I 'll look into how easy it is to do.

**Comment by jajhall** [comment]
Feature developed and #1181 will add it to `latest`

**Comment by jajhall** [comment]
You're welcome. What I did was fairly easy. However, since the MIP solver spawns sub-MIPs, I'm not sure whether their LP counts are added into the parent's accounting. Since the number of LP iterations is used to make tactical decisions in the MIP solver, I don't want to add them in and mess things up. I have to trust the MIP developer.
