### ISSUE TITLE
A question of numerical accuracy

### ISSUE THREAD

**Issue by tu3256076** [ERGO-Code/HiGHS#1292]
In my model, the result of the 0,1 variable calculated by highs is 0.9999991, which causes the calculation result to be different from the assumption (the meaning of the constraint expression has changed).

Can I set the result of the 0,1 variable strictly to the true 0,1 value

**Comment by jajhall** [comment]
Mathematically you can't guarantee that if you set the 0.9999991 value to 1 then you'll get the exact integer optimal solution. If nothing else, since the perturbation would be 9e-7, it's possible that some constraint could be violated by more than the feasibility tolerance of (default) 1e-7. 

Computational optimization solvers will generally only solve a problem to within tolerances. 

That said, rounding to 1 when the difference is so small will give the exact optimal integer solution with high probability.

Some doubts can be eased by taking the rounded solution, passing it back to HiGHS and solving the problem again. If the solution is feasible HiGHS will use it to get a bound on the optimal integer solution and probably return with proven optimality very quickly.

You could also try to reduce the mip_feasibility_tolerance option (default 1e-6) to see whether HiGHS "settles" on the exact integer value, but this can have adverse numerical consequences.

**Comment by tu3256076** [comment]
Thanks for your reply, by setting the appropriate mip_feasibility_tolerance and large M value, I have now avoided this problem.
