### ISSUE TITLE
HiGHS Infeasible when Presolve is Off

### ISSUE THREAD

**Issue by erdembanak** [ERGO-Code/HiGHS#1297]
For some problems, HiGHS returns the problem as infeasible when CPLEX and CBC find the optimal solution (3.1108620188e+11). Since there were issues about presolve, I have switched off presolve but the problem is still infeasible.

[infeasible_presolve_off.mps.txt](https://github.com/ERGO-Code/HiGHS/files/11518293/infeasible_presolve_off.mps.txt)

**Comment by jajhall** [comment]
Thanks!

**Comment by jajhall** [comment]
Just run this with Gurobi and it says, 

>   Matrix range     [1e+00, 1e+09]
  Objective range  [1e+00, 1e+00]
  Bounds range     [1e+00, 1e+00]
  RHS range        [1e-01, 2e+03]
Warning: Model contains large matrix coefficients
         Consider reformulating model or setting NumericFocus parameter
         to avoid numerical issues.

and,  although it finds a solution with objective `3.110862018838e+11`,

> Warning: max constraint violation (1.8311e-04) exceeds tolerance

So, since the problem may be infeasible to within the primal tolerance, it may be futile to try to identify whether HiGHS is actually wrong
