### ISSUE TITLE
Add a branch-and-price example for the python interface

### ISSUE THREAD

**Issue by guifcoelho** [ERGO-Code/HiGHS#1472]
Hello everyone, as mentioned [here](https://github.com/ERGO-Code/HiGHS/discussions/1466) I was supposed to provide an example of a branch-and-price algorithm using Highs. I will be submitting a pull request shortly.

**Comment by guifcoelho** [comment]
Submitted the pull request [1473](https://github.com/ERGO-Code/HiGHS/pull/1473).

**Comment by jajhall** [comment]
I ran your original file, and it triggered an assert in HiGHS. This is due to you passing a repeated index to 'changeColsBounds' in line 302 of `branch-and-price.py'. My logic was that if the same index is passed twice, the user might not get the bound change that's expected. In your case, you're passing the same value for all the lower bounds, and the same value for all the upper bounds, so there's no ambiguity. 

HiGHS should probably give a warning logging message, and return `HighsStatus.kWarning`, but I can't change this in PyPI

I can only guess that you don't see this assert, and I'm wondering why the C++ was compiled in anything other than `release`! Once again, nothing can be changed until we've restored the ability to push to PyPI. 

I get the duplicated index for 

> N = 60
> capacity = 15

making it rather more reproducible than with the original values of `N` and `capacity`

I also note that in the commented-out lines, starting at 295, you pass lower bounds of 0, but in the active code you pass lower bounds of 1. I don't know what you're doing algorithmically at this point, but I thought I'd flag it up in case there was an unintentional copy-paste error.

**Comment by guifcoelho** [comment]
Hello Julian!

> I ran your original file, and it triggered an assert in HiGHS. This is due to you passing a repeated index to 'changeColsBounds' in line 302 of `branch-and-price.py'. My logic was that if the same index is passed twice, the user might not get the bound change that's expected, so HiGHS demands strictly distinct indices in the set. In your case, you're passing the same value for all the lower bounds, and the same value for all the upper bounds, so there's no ambiguity and, without the assert, you'll get the change you wish.
> 
> HiGHS should probably give a warning logging message, and return HighsStatus.kWarning, but I can't change this in PyPI
> 
> I can only guess that you don't see this assert, and I'm wondering why the C++ was compiled in anything other than release! Once again, nothing can be changed until we've restored the ability to push to PyPI.

Yes, you are right. I don't get any errors or warnings when I do that. My aim here was to change the bounds so I could force the selected columns to be 1. One thing worth of mentioning is that I ran this with the current version in PyPI (1.5.3). Do you have any suggestions on how I could approach this?

> I get a duplicated index (of 165 when the set reaches a size of 24) for
> 
> N = 60
> capacity = 15
> 
> making it rather more reproducible than with the original values of N and capacity.

I will take a look into it. Does that give you an error?

> Am I correct in thinking that in the commented-out lines, starting at 295, when you pass lower bounds of 0, you were setting the bounds back to [0, 1], but that was "slower". In the active code you pass lower bounds of 1. I guess that these are the columns fixed to 1 at the node, so the difference isn't an unintentional copy-paste error

Yes, you are right. Since I was trying to iterate on only one model object for the Master Problem I had to revert the bounds of all columns back to `[0, 1]` before enforcing the selected ones to `[1, 1]`. However, I realised that creating a new model from scratch was actually faster for some reason. Should I use constraints instead of changing bounds? I didn't want to enforce it with constraints because I would probably need to add their duals on the pricing problem, if I'm not wrong.

**Comment by jajhall** [comment]
I'm running highspy 1.5.3, but on Linux. Maybe that explains why I see the assert. What's your architecture?

The duplicate index causes the assert.

I can't update what's on PyPI at present, so the only scope of a fix is with you. 

Thanks

**Comment by guifcoelho** [comment]
Hello, I found the problem with the duplicate index you mentioned. I was trying to be clever and was reseting the master problem some times and I was forgeting that I had changed some of the bounds of the variables during the branch-and-price part. Anyway... I've added some asserts to make sure that it does not happen anymore.

Would you mind trying to run it again? I've just pushed a new pull request.
