### ISSUE TITLE
Bug: Optimal solution with binary variable constraints is infeasible

### ISSUE THREAD

**Issue by marwingen** [ERGO-Code/HiGHS#1527]
First, thank you very much for your effort with this project. It is a real game changer for the open source solver reliant work 🙏 

It seems there is a bug in the handling of binary variable constraints.

Steps to reproduce in python (with highspy 1.5.3 installed via pip) with the attached `model.lp` file:

[model.lp.txt](https://github.com/ERGO-Code/HiGHS/files/13453164/model.lp.txt)

```python
import highspy
h = highspy.Highs()
filename = "model.lp"
h.readModel(filename)
h.run()
h.writeSolution("solution.txt", 0)
```

This produced the attached `solution.txt` file.

[solution.txt](https://github.com/ERGO-Code/HiGHS/files/13453165/solution.txt)

In the `model.lp` file the variable `x168` is defined as binary (line 2198):

```
binary

x168
x169
...
```

A constraint `c397` is defined in line 1899 ff.:

```
c397:
-1 x50
+1e-08 x168
<= -0
...
```

In the produced `solution.txt` file the values for `x50` (line 44) and `x168` (line 177) are given as:

```
x50 0
...
x168 1
...
```

This violates the constraint `c397`:

```
-1 x50 +1e-08 x168 <= -0
-1   0 +1e-08    1 <=  0
     0 +1e-08      <=  0 which is not true
```

Therefore the proposed solution should be infeasible. Or do I miss something?

CBC and GLPK do not have this issue. They get to a optimal and feasible solution.

**Comment by jajhall** [comment]
HiGHS (like any practical software) solves problems to within tolerances. For `x50=0` and `x168=1`, the activity of constraint `c397` is `1e-08`. Although the bound is `<=0`, the activity satisfies the bound to within the (default) `mip_feasibility_tolerance` of 1e-06. Hence the solution returned by HiGHS is feasible

If `mip_feasibility_tolerance` is set to 0.99e-08, then HiGHS yields the solution

- x50 0
- x168 0
- c397 0

The same solution is obtained using `mip_feasibility_tolerance=1e-06`, if the coefficient of `x168`, in constraint `c397` is changed to `1.01e-06`.

Since CBC and GLPK will solve using a similar tolerance, it' probably just chance that they find the `x168=0` before the solution obtained by HiGHS.

I note that the optimal objective values of both Gurobi (1.249985942024e+06) and HiGHS (1.249985942207e+06) are equal to within normal tolerances.
