### ISSUE TITLE
PuLP Interface

### ISSUE THREAD

**Issue by zepedropaulos** [ERGO-Code/HiGHS#1538]
Having some issues defining the gapRel/mip_abs_gap option with the PuLP integration. The PuLP documentation states that HiGHS_CMD implementation should have the gapRel parameter, but the HiGHS_CMD function does not accept it. HiGHS documentation states that it can be configured via options and mip_abs_gap parameter. However, I'm not able to add this option in my code. Alread tried:

```
milp.setSolver(HiGHS_CMD(msg=True, timeLimit=100, options=['mip_abs_gap=0.001'], path=highs_path))
milp.setSolver(HiGHS_CMD(msg=True, timeLimit=100, options='mip_abs_gap=0.001', path=highs_path))
milp.setSolver(HiGHS_CMD(msg=True, timeLimit=100, mip_abs_gap=0.001, path=highs_path))
milp.setSolver(HiGHS_CMD(msg=True, timeLimit=100, gapRel=0.001, path=highs_path))
```

But everything returns an error. How am I supposed to enter the options?

**Comment by jajhall** [comment]
Sorry, I don't know, as this is a PuLP issue, not a HiGHS issue. I say this because PuLP parses the options and then sets corresponding options for a particular solver.  For example, `timeLimit` isn't a HiGHS option: we have `time_limit`.

Note that HiGHS has both [`mip_abs_gap`](https://ergo-code.github.io/HiGHS/stable/options/definitions/#mip_abs_gap) and [`mip_rel_gap`](https://ergo-code.github.io/HiGHS/stable/options/definitions/#mip_rel_gap).
