### ISSUE TITLE
Trying to get C# to run

### ISSUE THREAD

**Issue by Doidel** [ERGO-Code/HiGHS#1659]
I fail to get the C# integration with P/Invoke to run. I added the two files highs.exe (from Julia) and the zlib ([also from Julia](https://github.com/JuliaBinaryWrappers/Zlib_jll.jl/releases)) into the C# project. Then I adjusted the `highslibname` from "highs" to "highs.exe".

When I run the exe in cmd it works fine, I could even load a small .mps and run it. But when I try to run the C# program I get:
`Unable to find an entry point named 'Highs_create' in DLL 'highs.exe'.`

From [the documentation](https://ergo-code.github.io/HiGHS/dev/interfaces/other/#C#) I expected to find multiple DLLs in the Julia binaries, but I only found a single Exe and multiple C++ header files. What am I missing?

Thanks for your help!

**Comment by jajhall** [comment]
I've no idea what this is about, as most of our C# interface has been written by external contributors

**Comment by metab0t** [comment]
If you download HiGHS from Julia and want to use the dynamic library, you should download from https://github.com/JuliaBinaryWrappers/HiGHS_jll.jl instead of https://github.com/JuliaBinaryWrappers/HiGHSstatic_jll.jl. The latter only contains the static build of executable without the dynamic library.

The Julia version relies on some GCC-related stuff and zlib dependency, and you must download it manually.

I also set up a binary distribution of HiGHS at https://github.com/metab0t/highs_autobuild built by Github Actions. It uses MSVC on Windows and disabled third-party dependency on zlib, so the distribution can be used out of the box.

**Comment by odow** [comment]
Yes, you can't jut change the `.exe` extension to `.dll`. You need to use the releases from HiGH_jll.jl.

I should revisit: https://github.com/ERGO-Code/HiGHS/issues/746. It would be useful if we could provide a single download for people and upload them a release asset to this repo.

**Comment by odow** [comment]
https://github.com/metab0t/highs_autobuild is cool though. Perhaps we could just adapt that here, or add something similar to `ERGO-Code`.

**Comment by jajhall** [comment]
Many thanks to @metab0t and @odow

**Comment by Doidel** [comment]
It's running now, thanks for the link correction!

Indeed for future C# users an easier setup would be appreciated. Maybe even autogenerate a NuGet package instead of "just" the P/Invoke interface bundled with the binaries :)

Again, much appreciated!

**Comment by jajhall** [comment]
Thanks, we are considering creating a nuGet package
