### ISSUE TITLE
turn off `presolve` would return worse result

### ISSUE THREAD

**Issue by mzy2240** [ERGO-Code/HiGHS#1696]
I am trying to tune the HiGHS on a MIP problem and happen to find out that HiGHS returns worse result if switching off the presolve. I have attached the case that should help reproduce the issue. With `mip_rel_gap=0.0005`, I am able to get `2.084748238572568e6` when presolve is enabled and `2.0849273612253e6` when presolve is disabled. This is a minimization problem. I am running HiGHS v1.7.0 on a M1 Max machine.
[model_1.mps.zip](https://github.com/ERGO-Code/HiGHS/files/14783545/model_1.mps.zip)
<img width="358" alt="image" src="https://github.com/ERGO-Code/HiGHS/assets/18620336/d63edda3-c480-43cb-8770-f7f2ef23ad5e">

**Comment by mzy2240** [comment]
dont think it is related to `HiGHS.jl` but loop @odow in just in case

**Comment by jajhall** [comment]
I'll look at this.

**Comment by jajhall** [comment]
This isn't a bug, but it was interesting to observe

Here are 
- the optimal objective, obtained by running HiGHS and Gurobi with a gap tolerance of 0.0
- primal (upper) and dual (lower) bounds obtained by running HiGHS and Gurobi with your gap tolerance of 0.0005

![image](https://github.com/ERGO-Code/HiGHS/assets/22636003/032e4640-4299-4770-add2-88e3196dabc6)

With a gap tolerance of 0.0005...

- HiGHS with presolve finds the optimal solution of 2084748.23857, and stops with a smaller dual (lower) bound of 2084172.97145 because the relative gap of 0.000276 satisfies the tolerance

- HiGHS without presolve gets a sub-optimal solution with objective 2085446.34169, but stops because it had a larger dual (lower) bound of 2084650.38456, so the relative gap of 0.000382 satisfies the tolerance

- Gurobi without presolve gets a sub-optimal solution with objective 2085148.187359, but stops because it had a larger dual (lower) bound of 2084533.829127, so the relative gap of 0.000295 satisfies the tolerance

**Comment by mzy2240** [comment]
Make sense. Thank you for the investigation!
