### ISSUE TITLE
Compiler warnings due to `src/parallel/HighsSplitDeque.h`

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#1907]
Just updated Ubuntu, and now get 

> /home/jajhall/HiGHS/src/parallel/HighsSplitDeque.h:261:19: warning: offset of on non-standard-layout type 'HighsSplitDeque' [-Winvalid-offsetof]
  261 |     static_assert(offsetof(HighsSplitDeque, splitRequest) == 64,
      |                   ^                         ~~~~~~~~~~~~
/usr/lib/llvm-18/lib/clang/18/include/__stddef_offsetof.h:16:24: note: expanded from macro 'offsetof'
   16 | #define offsetof(t, d) __builtin_offsetof(t, d)
      |                        ^                     ~

for this and lines `263`, `265` and  `267`.

No idea what this means or how to fix it.

Code was written by @lgottwald three years ago

**Comment by fwesselm** [comment]
This is speculation because I was not successful in reproducing this, but the compiler seems to say that class `HighsSplitDeque` is not in standard layout (anymore).

To double check I have put the following assert before the problematic block starting in line 261:

`static_assert(std::is_standard_layout_v<HighsSplitDeque>, "not standard layout");`

I hope it's not an issue with the (updated) compiler on your side.

**Comment by jajhall** [comment]
Thanks, I don't know enough to comment

**Comment by fwesselm** [comment]
Just an additional data point: I created a branch and added the above assertion, which makes `build-linux` and `build-clang` fail while `build-windows` runs fine.

**Comment by lgottwald** [comment]
I remember that I added the assertion just to ensure proper alignment with cache line boundaries. The compiler warning just seems to be about using offsetof for this particular class as you have discussed.
To avoid the warning the assertion could be removed or the warning disabled or the alignment could be asserted by a runtime assert in the constructor.

When the static assert fails nothing will break only performance might be affected.
