### ISSUE TITLE
Highs_setOptionValue unimplemented

### ISSUE THREAD

**Issue by matbesancon** [ERGO-Code/HiGHS#223]
I don't find any implementation of the Highs_setOptionValue function, which is only defined in the C interface but not in the shared object.

**Comment by mlubin** [comment]
@jajhall, https://github.com/ERGO-Code/HiGHS/commit/d23eca2c84a817fc4d03ee34d58fac7ea42ece0a appears to have addressed this issue. Should we start adapting the Julia wrapper or should we wait for more changes?

**Comment by jajhall** [comment]
I didn't create a full set of getters and setters in the C interface. HiGHS has options of bool, int, double and string type. There are still only setters for int, double and string (as char*), and getters for int and double. I'm afraid my C/C++ skills aren't up to the others. Note that we created setHighsOptionValue in the C interface when we were going to pass all values of options as strings. In the C++ interface we now we allow them to be passed as bool, int, double, string by overloading the definition of setHighsOptionValue. In the C interface I created setHighsIntOptionValue, setHighsDoubleOptionValue and setHighsStringOptionValue to achieve the same functionality, leaving setHighsOptionValue rather than delete it from the API. I'll get @feldmeier on the case to do a proper job, but opinions from others would be welcome.

**Comment by feldmeier** [comment]
I added the getter/setter for bool and the getter for string options in #299. For retrieving a string option the user needs to provide a pointer to a sufficient amount of memory. There is no good way of handling the memory allocation for the user in this case.
