### ISSUE TITLE
BUG: IPX incorrect solution

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#295]
Consider the following unbounded problem (based on scipy issue [#8973](https://github.com/scipy/scipy/issues/8973) and unit test [test_bug_8973](https://github.com/scipy/scipy/blob/master/scipy/optimize/tests/test_linprog.py#L1264)):
```
c = [0, 0, 0, 1, -1]
A = [
    [1, 0, 0, 0, 0],
    [0, 1, 0, 0, 0],
]
lhs = [-inf, -inf]
rhs = [2, -2]
lb = [-inf, -inf, -inf, -1, -1]
ub = [inf, inf, inf, 1, 1]
```

While the simplex solver (without presolve) gets a correct solution, IPX (without presolve) reports the correct objective function value but reports an inconsistent solution.  Both simplex and IPX report error when presolve is on.

Simplex gives: `primal = [0, -2, 0, -1, 1]` with `objective_fun = -2`
IPX gives: `primal = [0, -2, 0, 0, 0]` with `objective_fun = -2` , but `c @ primal` is not `-2`, so either the primal solution is incorrectly reported or the objective function value is incorrectly reported.

Summary:
- IPX reports incorrect solution
- Simplex/IPX fail when presolve is enabled

MPS file:
[test.txt](https://github.com/ERGO-Code/HiGHS/files/4427771/test.txt)

**Comment by mckib2** [comment]
Using latest build results in warning with no solution written to file:
```
Model   status      : Optimal
Simplex   iterations: 0
IPM       iterations: 4
Objective value     : -2.000000e+00
warning: Feature under development
```

**Comment by jajhall** [comment]
Thanks for this. Firstly the LP isn't unbounded - I got worried when HiGHS without presolve found an optimal solution! The solution is non-unique, as the first three variables can be made arbitrarily large (with the right sign) without changing the objective. 

HiGHS Presolve eliminates both rows, and all but the free variable. Since the LP can then be solved by inspection, HiGHS doesn't call simplex or IPX.

With bugfixes now in master

HiGHS Presolve+Solve, and IPX now all give an optimal solution. 

Note that "no solution written to file" came as a surprise to me! The code for this has been temporarily commented out, since its use of printf and fprintf was causing a problem for the JuliaOpt guys. I'll get this restored as soon as possible!

**Comment by jajhall** [comment]
I'll leave it for you to close

**Comment by mckib2** [comment]
Great!  I'll take a look at this and make sure I can reproduce it

**Comment by mckib2** [comment]
Unit test is now passing, closing issue.
