### ISSUE TITLE
PowerPC build failing

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#304]
Building on [ppc64le](https://en.wikipedia.org/wiki/Ppc64) is failing at [this include](https://github.com/ERGO-Code/HiGHS/blob/master/src/util/HighsTimer.h#L23):
```
#ifdef _MSC_VER
#include <intrin.h>
#else
#include <x86intrin.h>
#endif
```

It appears ppc64 has Power-specialized subcomponents of mmintrin.h (MMX), xmmintrin.h (SSE) and emmintrin.h (SSE2) (see [here](https://www.talospace.com/2019/07/easier-power-vectorizing-for-fun-and.html)).

**Comment by rgommers** [comment]
`x86intrin.h` was only implemented in GCC in mid-2017 - see history of [gcc/config/rs6000/x86intrin.h](https://github.com/gcc-mirror/gcc/commits/master/gcc/config/rs6000/x86intrin.h) and [this patch proposal](https://gcc.gnu.org/legacy-ml/gcc-patches/2017-05/msg00550.html). I suspect a too old compiler is being used here. @mckib2 can you link to a build log and confirm the gcc version you're using? I don't remember what the current minimum gcc for SciPy is; either 4.9 or 5.2 I believe.

That said, there are other compilers and platforms where I'd expect `x86intrin.h` to also be problematic. Maybe the maintainers can comment on whether its use is really needed.

**Comment by feldmeier** [comment]
As far as I remember this header is only used for __rdtsc() to get timing information (CPU ticks) in HighsTimer. Sometimes ticks are used for timing, and sometimes wall clock (for which we use std::chrono) is used. I can't comment on how important the #ticks is. @jajhall

**Comment by mckib2** [comment]
> @mckib2 can you link to a build log and confirm the gcc version you're using?

@rgommers [Link](https://travis-ci.org/github/scipy/scipy/jobs/673273371) to failed CI log ([line where build fails](https://travis-ci.org/github/scipy/scipy/jobs/673273371#L8499)).

[Line 32/33](https://travis-ci.org/github/scipy/scipy/jobs/673273371#L32) give the following:
```
GCC version
gcc (Ubuntu/IBM 5.4.0-6ubuntu1~16.04.12) 5.4.0 20160609
```

**Comment by mckib2** [comment]
This seems related to #215

**Comment by rgommers** [comment]
> An answer in [this](https://stackoverflow.com/questions/11228855/header-files-for-x86-simd-intrinsics) stackoverflow answer notes that "gcc : support for `x86intrin.h` first appears in `gcc-4.5.0`", so am I misreading the log/config files? Seems like gcc-5.4.0 should have this header

You're not misreading the log. It may have been first introduced there, but it did not support all platforms. PowerPC support is definitely very recent. There'll be problems on other platforms as well, the current code is definitely not portable.

> This seems related to #215

Good catch, same issue.

**Comment by rgommers** [comment]
From https://en.wikipedia.org/wiki/Time_Stamp_Counter:

_Relying on the TSC also reduces portability, as other processors may not have a similar feature. Recent Intel processors include a constant rate TSC (identified by the kern.timecounter.invariant_tsc sysctl on FreeBSD or by the "constant_tsc" flag in Linux's /proc/cpuinfo). With these processors, the TSC ticks at the processor's nominal frequency, regardless of the actual CPU clock frequency due to turbo or power saving states. Hence TSC ticks are counting the passage of time, not the number of CPU clock cycles elapsed._

_On Windows platforms, Microsoft strongly discourages using the TSC for high-resolution timing for exactly these reasons, providing instead the Windows APIs `QueryPerformanceCounter` and `QueryPerformanceFrequency`. On POSIX systems, a program can get similar function by reading the value of CLOCK_MONOTONIC clock using the `clock_gettime` function._

@feldmeier can C++11 be used? If so, using `std::chrono::system_clock` seems better to use here to get wall clock time.

**Comment by feldmeier** [comment]
C++11 is the standard we use, and we use std::chrono for some of the timing already. @jajhall will have to say how the #ticks are being used and what would need to be modified to use system_clock instead

**Comment by jajhall** [comment]
With one exception, the (wall clock) time and (system) ticks are used for performance analysis when developing the code. All I need is a high-resolution, low-cost method of finding the wall clock time. Historically - and I've been coding high performance simplex solvers for 25 years, so may well have out-of-date ideas :-) - getting the wall clock time had a significant overhead and didn't have great resolution. Hence I've tended to use ticks to create most records. However, a "HiGHS clock" that is called relatively infrequently maintains records of both time and ticks. These records are used to calibrate the ratio between time and ticks, allowing records generated using ticks to be reported as time.
 
The only timer _required_ by the HiGHS production code is the "HiGHS clock" used to determine whether the solvers should time-out. 

If someone can suggest a universal means of making wall time calls - that is of low cost and high resolution using gcc on Linux - then this is sufficient, and I don't need ticks. 

For reference, Qi (in c2012) only used ticks to do his profiling, 

#include <sys/time.h>

    double getWallTick() {
        unsigned a, d;
        asm volatile("rdtsc" : "=a" (a), "=d" (d));
        return ((unsigned long long) a) | (((unsigned long long) d) << 32);
    }

but also used

    double getWallTime() {
        double walltime;
        struct timeval tv;
        gettimeofday(&tv, NULL);
        walltime = tv.tv_sec;
        walltime += (double) tv.tv_usec / 1000000.0;
        return walltime;
    }

However, this - I guess - is very Linux-specific.

**Comment by jajhall** [comment]
Doing experiments with https://github.com/jajhall/Timing, (on a Linux desktop using g++ TImer.cpp) and with reference to
https://www.modernescpp.com/index.php/the-three-clocks 
there is no difference between the three clocks, the resolution looks fine, and the relative cost of time rather than tick calls is not significant.

I'll see how it runs on Windows and a Mac

Any comments?

**Comment by rgommers** [comment]
> @rgommers [Link](https://travis-ci.org/github/scipy/scipy/jobs/673273371) to failed CI log ([line where build fails](https://travis-ci.org/github/scipy/scipy/jobs/673273371#L8499)).

Since TravisCI had an outage today, and the logs won't stay up forever anyway, I'll copy the issue here:
```
scipy/optimize/_highs/src/util/HighsTimer.h:26:23: fatal error: x86intrin.h: No such file or directory
compilation terminated.
```


> Doing experiments with https://github.com/jajhall/Timing, (on a Linux desktop using g++ TImer.cpp) and with reference to
> https://www.modernescpp.com/index.php/the-three-clocks
> there is no difference between the three clocks, the resolution looks fine, and the relative cost of time rather than tick calls is not significant.

I've been reading a bit about this; conclusion is that there's no off-the-shelf problem-free approach that is portable, high resolution and low-cost. Ticks also aren't standardized across platforms.

The low-cost high-res requirement just seems to apply to Linux though, and there indeed it seems fine (as you found). On other platforms it just needs to work. A couple of the best explanations I found:
- https://blog.quasardb.net/2014/06/07/a-portable-high-resolution-timestamp-in-c
- https://bduvenhage.me/performance/2019/06/22/high-performance-timer.html

This MIT-licensed repo compares a few approaches in detail (connected to the last link above): https://github.com/bduvenhage/Bits-O-Cpp/tree/master/time

Using either of your Linux-specific implementations on `x86_64` hardware, and using `std::chrono::high_resolution_clock` (as [here](https://github.com/bduvenhage/Bits-O-Cpp/blob/master/time/main_cpp11_chrono.cpp#L59)) on all other platforms should work.

**Comment by jajhall** [comment]
Thanks @rgommers I've now run my Timing code on Linux, Windows and Mac, and the high resolution clock is fine. I'll get references to tick (and hence x86intrin.h) removed 

FWIW, 
- On Linux: all three clocks (system, steady and high_resolution) cost about the same and have the same resolution - probably equivalent - and tick is 1/3 of the overhead.

- On Windows: the system clock has lower resolution and is a little faster. The other two are comparable. Tick is about 10 times faster 

- On Mac: all three clocks (system, steady and high_resolution) have the same resolution but the system clock is twice as expensive. Tick is 1/3 of the overhead of steady and high_resolution

[Timing.txt](https://github.com/ERGO-Code/HiGHS/files/4465367/Timing.txt)

**Comment by jajhall** [comment]
Right! master now has no reference to <intrin.h> or <x86intrin.h> so has a fighting chance of building everywhere!

**Comment by mckib2** [comment]
@jajhall Appreciate you getting this worked out so quickly!

Ref pull request #313 .  Will close this issue as original error has been resolved.

**Comment by rgommers** [comment]
Thanks @jajhall, all!
