### ISSUE TITLE
How to get dual solution/slack values

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#315]
HighsSolution returns the following:
```
col_value
col_dual
row_value
row_dual
```
`col_value` is the primal solution.  After looking at the results from each of the rest of these, it appears the dual solution and/or slack values are not reported.  Is there a way to get at the dual solution and/or slack values?

**Comment by mckib2** [comment]
Take the simple example with only equality and nonzero constraints from [Wikipedia](https://en.wikipedia.org/wiki/Revised_simplex_method):
```
c = [-2, -3, -4, 0, 0]
A = [
    [3, 2, 1, 1, 0],
    [2, 5, 3, 0, 1],
]
b = [10, 15]
lb = [0, 0]
```

The answer we expect:
```
x = [0, 0, 5, 5, 0]
lambda: [0, -4/3]
s: [2/3, 11/3, 4/3]
```
where `lambda` and `s` are the Lagrange multipliers associated with the constraints `Ax = b` and `x>=0`, respectively.

Consider the results of HiGHS:
```
col_value: [0., 0., 5., 5., 0.] # primal solution
col_dual: [0.6666666666666665, 3.666666666666666, 0.0, 0.0, 1.3333333333333333]
row_dual: [0.0, 1.3333333333333333]
```
It appears that:
- the negated entries of `row_dual` are equivalent to `lambda`?
- the nonozero entries of `col_dual` are equivalent to `s`?

Further, when there are inequality constraints, where can the slack values be found?

**Comment by jajhall** [comment]
There are always (virtual) slacks in HiGHS, whatever bounds the constraints have. HiGHS solves the LP with slacks s=Ax, (ie Ax-s=0) so that the slacks have the same bounds as the constraints. Thus the slacks are the "rows", and their values are in row_value.

Yes, the negated entries of row_dual are equivalent to lambda. The sign difference comes from the fact that the slacks in HiGHS appear as Ax-s, rather than Ax+s, and means that the row duals give the fair price for increasing a lower bound or decreasing an upper bound, the same way as the column duals for their bounds.

Although it's conventional to "add" slacks so that Ax<=b becomes Ax+s=b, s>=0, this is inconvenient when handling general bounded LPs.

**Comment by mckib2** [comment]
Thanks for your response, I now understand how HiGHS handles slack.
