### ISSUE TITLE
Retrieve premature solution

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#324]
@jajhall It appears that HighsSolution object is not populated when iteration limit is reached for either simplex or ipm methods.

The simplex method should always have a feasible solution, is there a way to retrieve the current feasible solution should iteration limit be reached?  Interior-point may not have any useful information before optimal solution is reached, but maybe you could comment on if any solution is available for ipm if iteration limit is reached?

**Comment by jajhall** [comment]
A feasible solution is generally _not_ available. 

HiGHS uses the dual simplex method, so a (primal) feasible solution is only obtained when the LP is solved to optimality. 

Even when the primal simplex algorithm is used, there is no feasible solution until phase 2.

Interior point, on the other hand, may well have a feasible solution (both primal and dual) well before reaching the optimal solution [What's missing is the complementarity of the primal and dual solutions.]

I've given some thought to whether to return a dual feasible solution if the simplex solver in HiGHS is interrupted by time or iterations (or otherwise), or when the LP is found to be infeasible, but felt that it wasn't worth it.

You can see whether a primal (dual) solution is available by inspecting the value of info_.primal_status (info_.dual_status). If it's PrimalDualStatus::STATUS_FEASIBLE_POINT [which currently has the value 3 when calling vial C] then the row/column solution vector is allocated and contains a feasible point.

**Comment by mckib2** [comment]
> You can see whether a primal (dual) solution is available by inspecting the value of info_.primal_status (info_.dual_status).

This is the info I needed, thanks!

...

We might also be interested in warm and/or hot starting.  It looks like this may have been considered before (see [here](https://github.com/ERGO-Code/HiGHS/commit/b870ac8a6492794717493f54741f20ab17b6bc80)), but I'm curious to know if there are any undocumented methods available for warm starts

**Comment by mckib2** [comment]
> You can see whether a primal (dual) solution is available by inspecting the value of info_.primal_status (info_.dual_status).

This does not seem to be working all of the time.  I have a few test cases that return an optimal solution that can be read from a HighsSolution object but which report `PrimalDualStatus::STATUS_NOT_SET` for both `primal_status` and `dual_status`.

What I have been doing before is simply checking that the `model_status` is one of 
```
HighsModelStatusNOTSET,
            HighsModelStatusLOAD_ERROR,
            HighsModelStatusMODEL_ERROR,
            HighsModelStatusMODEL_EMPTY,
            HighsModelStatusPRESOLVE_ERROR,
            HighsModelStatusSOLVE_ERROR,
            HighsModelStatusPOSTSOLVE_ERROR,
            HighsModelStatusPRIMAL_INFEASIBLE,
            HighsModelStatusPRIMAL_UNBOUNDED,
            HighsModelStatusREACHED_ITERATION_LIMIT
```
before attempting to read the row/column solution vector.  This method appears to work whereas checking `info_.primal_status` does not.

This might be due to a mistake I've made, so I'll make an MPS file trying to demonstrate this

**Comment by jajhall** [comment]
You're getting to the cutting edge of things that work reliably in HiGHS. The other day I spotted that an optimal model status didn't have the right values set for info_.primal_status. There's a fix in a branch of recent stuff that needs to be merged into master, but I've just discovered that I've broken something in the simplex solver, so I need to fix this first.

Getting efficient re-optimization after modifying the problem is "under development", and is non-trivial to get right. But, we need it for our MIP solver and the interface I'm writing to allow HiGHS to be used as the LP solver in SCIP. Most of what's required is written, and both projects solve some MIPs, but it needs debugging. [Hence the warning messages when you call LP modification methods]

Unfortunately I've not designed the code as well as I should as I migrate from HiGHS being an interface to a single (parallel) dual simplex solver for one-off LPs, to one that allows LP modification and solution using a range of solvers within a proper piece of optimization software!

**Comment by mckib2** [comment]
Here is an MPS file based on [this](https://github.com/scipy/scipy/blob/fc85c265d3f79a0011c7b988ac2cbd25d757550a/scipy/optimize/tests/test_linprog.py#L1012) unit test that produces an optimal solution but which has info_.primal_status == -1. Hopefully it will help with your testing:
[test6139.txt](https://github.com/ERGO-Code/HiGHS/files/4494008/test6139.txt)

> Getting efficient re-optimization after modifying the problem is "under development", and is non-trivial to get right. But, we need it for our MIP solver ...

MIP was also the use case that warm start arose in. I can appreciate the non-triviality :)

**Comment by jajhall** [comment]
Yes, the new branch already fixed this issue

**Comment by mckib2** [comment]
Great!  I'll wait till https://github.com/ERGO-Code/HiGHS/tree/Issue324 is merged into master to close out

**Comment by jajhall** [comment]
Fixed by recent merge into master

**Comment by mckib2** [comment]
This appears to be working as expected.
