### ISSUE TITLE
Expose one-sided bound changes

### ISSUE THREAD

**Issue by matbesancon** [ERGO-Code/HiGHS#326]
This applies to both row and column bounds, changing bounds currently requires passing both sides:

```c
int Highs_changeColBounds(
    void* highs,         //!< HiGHS object reference
    const int col,       //!< The index of the column whose bounds are to change
    const double lower,  //!< The new lower bound
    const double upper   //!< The new upper bound
);
```

In many cases, the users manipulates one-sided inequalities and will like to change them this way. Currently this requires first getting the column bounds (there is no individual getCol, only get multiple columns at a time), updating one of the two bounds and re-passing the new values to the solver.

I could be wrong but this double round trip seems like a significant overhead for which it could be worth adding a function to the interface

**Comment by jajhall** [comment]
There's no need to get the column bounds first. Other than the documentation overhead, it's easy to create one-sided methods to change just one column/row lower/upper bound, but do we then have the same things for multiple columns/rows - in all the ways that they can be defined - and the versions where all rows/column bounds are to be changed to a single value, rather than an array of values. It starts to get horribly combinatorial.

There is, however, the question for users with one-sided inequalities - lower-bounded, say - remains: "What do I pass as upper?"

Would it be sensible to have a method defining "HiGHS infinity" - which is about to become std::numeric_limits<double>::infinity()? This would allow "nice" calls like

  const double inf = Highs_getHighsInfinity(highs);
  Highs_changeColBounds(highs, 0, l, inf);

**Comment by odow** [comment]
I believe this question came from the Julia wrapper. We don't need this anymore, and yes, passing `inf` works fine.

**Comment by matbesancon** [comment]
OK I think this can be closed then? I'll let the HiGHS team decide

**Comment by jajhall** [comment]
Highs_getHighsInfinity(highs); has been implemented for a while now, so knowing the "right" value of inf to pass is easy
