### ISSUE TITLE
CMake version too high for Ubuntu 18.04

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#339]
The newest version of cmake available from official Ubuntu repositories is 3.10.2 (using Ubuntu 18.04).
```
cmake is already the newest version (3.10.2-1ubuntu2.18.04.1).
```

Is there a compelling reason for using 3.15 as updated in #335 ?  Happy to manually install newer version, but might be easier on users to require a reasonably recent version that's easily installed using default package managers.

**Comment by galabovaa** [comment]
Yes there is a reason, CMake introduces a lot of updates at 3.15 related to the way libraries are represented internally. We have yet to make our CMake "More Modern" since that guarantees targets and interfaces will be generated and linked correctly on all platforms. 

Manually downloading CMake from their website should be straightforward.
