### ISSUE TITLE
DOC: undocumented advanced options

### ISSUE THREAD

**Issue by mckib2** [ERGO-Code/HiGHS#342]
Not an urgent thing, but I noticed there were some undocumented options in HighsOptions.h.  I am including support for them in the scipy python wrapper and have them currently listed as undocumented advanced options.

Is there a place where these are documented?  If not, it might be helpful to at least make a note about if they are used or unused.

Specifically looking at these:
```c++
  // Advanced options
  bool run_as_hsol;
  bool mps_parser_type_free;   <-- already clear what this does
  int keep_n_rows;
  int allowed_simplex_matrix_scale_factor;
  int allowed_simplex_cost_scale_factor;
  int simplex_dualise_strategy;
  int simplex_permute_strategy;
  int dual_simplex_cleanup_strategy;
  int simplex_price_strategy;
  bool simplex_initial_condition_check;
  double simplex_initial_condition_tolerance;
  double dual_steepest_edge_weight_log_error_threshhold;
  double dual_simplex_cost_perturbation_multiplier;
  bool less_infeasible_DSE_check;
  bool less_infeasible_DSE_choose_row;
  bool use_original_HFactor_logic;
```

**Comment by jajhall** [comment]
Thanks. Documentation is lagging behind development at the moment!

**Comment by jajhall** [comment]
I've updated 

https://www.maths.ed.ac.uk/hall/HiGHS/HighsOptions.html

Setting update limit to 0 (or 1) means that HiGHS re-factorizes every basis matrix rather than updating the invertible representation [The inverse is never computed explicitly in HiGHS - for a host of reasons.] The code runs fine, but it'll be a lot slower on large problems!

dual_objective_value_upper_bound is used in only the dual simplex solver, and causes it to bail out when the objective (in Phase 2) reaches this limit. I's used to save time when the LP is a node from a MIP solver. 

The simplex crash is off by default because it's not so useful with the dual simplex method and there are some numerical issues with it on some large, hard test problems. Making the most of crashing is work on the stack.

Fundamentally, you're exploring options - the advanced ones, and a few others - that are only there for development. Unfortunately we don't have a "system" where there are options available to us to play with that aren't available to users.

**Comment by mckib2** [comment]
Since most of these are not user options, will close this issue

**Comment by jajhall** [comment]
> Since most of these are not user options, will close this issue

My point is that the advanced options are all available for a user to play with. This can be added to the "health warning" on the non-advanced options that the users shouldn't try.

My guess is that most users will just be solving one-off non-pathological LPs, so all will be well - even with IPX - so will be happy.

It won't be so long before the immediate loopholes through which HiGHS could be made to fail will be closed, but it's better for it to be "out there" in the meantime.

Thanks for your patience
