### ISSUE TITLE
status of parallel solving ?

### ISSUE THREAD

**Issue by lovasoa** [ERGO-Code/HiGHS#477]
Two years ago, the following was added to this project's readme : 

> At the moment the parallel option is temporarily unavailable due to a large
refactoring in progress. This document will be updated once we have completed
the interface currently being developed.

So, what is the current status of this refactoring ? Is there an estimated date when parallel solving will be available again ? Or is it already available, and it's just the readme that is outdated ?

**Comment by jajhall** [comment]
Parallel dual simplex is available in HiGHS under Linux - only, I think, due to problems using OpenMP on Windows (and Mac?) This situation should improve when we move over to the native C++ parallel instructions. However, performance gain is unlikely to be significant. At best, speed-up is limited to the number of memory channels, rather than the number of cores.

**Comment by jajhall** [comment]
Master RADME.md updated
