### ISSUE TITLE
Regarding the problem I found multiply_modM61

### ISSUE THREAD

**Issue by WTFHCN** [ERGO-Code/HiGHS#543]
I suddenly discovered it while appreciating the HIGHS code, and after thinking about it for a while, I corrected this part and wrote my own test. And **on Saturday** submitted a **[Pull requests](https://github.com/ERGO-Code/HiGHS/pull/539)**, and prepared a PDF to explain my principle, but @lgottwald , before he commented on the PR, he took the problems I found and submitted his **[Pull requests](https://github.com/ERGO-Code/HiGHS/pull/540)** on **Sunday night**, you can see time of our Pull request
(although his code looks more concise, in fact, I think I The two codes are similar, and they have been tested in time. On the contrary, I think my code understands better than him, but it is not important). Finally, lgottwald's own PR was merged into the master branch, and there were problems I found in it. But in the end I got nothing. Even my commit in the project has not increased at all (it seems that my idea has been stolen, I think I should also go in and modify it again on my modified branch, resulting in the PR is all the credit of lgottwald, my contribution to the community is all no). This does not seem to conform to the open source community norms. 
I am a student and used to be an algorithm contest player. I am interested in the HIGHS solver, hoping to contribute my own strength to the project, but I didn't get anything in the PR of my idea, which made me very uncomfortable.

**Comment by odow** [comment]
Hi @WTFHCN,

I'm not officially involved with HiGHS, so know that I don't speak for them. This is just coming from a personal experience with similar situation, and as an outsider who want's to see HiGHS succeed.

I see that you have put substantial effort into understanding the code! It's certainly a deep contribution to start with. I also know how the way the PRs were developed would leave you uncomfortable. The lack of attribution makes it harder to point to contributions you make when writing a CV or in job interviews.

The best course of action would have probably been to have used git's `co-authored-by` feature:
https://docs.github.com/en/github/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors
with the commit message that documented how the problem was found, and pointed to your PR. However, since the change has now landed on `master` the HiGHS team probably doesn't want to go in an re-write the history.

I will say: please don't let this one experience put you off. The HiGHS team is (very) small and relatively new to managing submissions from external contributors. It take time for projects to develop procedures and norms for how situations like this are handled. I'm sure they would welcome additional contributions in the future.

**Comment by WTFHCN** [comment]
thank you very much. and I will Continue to study the solver。
