### ISSUE TITLE
Change .pc file install location from lib/pkg-config to lib/pkgconfig

### ISSUE THREAD

**Issue by brechtsanders** [ERGO-Code/HiGHS#587]
**Problem**

The file `highs.pc` is installed under `lib/pkg-config`, but the normal place for `pkg-config` to look for `.pc` files is under `lib/pkgconfig`.

**Solution**

In `src/CMakeLists.txt` replace all occurrences of `lib/pkg-config` with `lib/pkgconfig`.

**Comment by jajhall** [comment]
@yurivict raised as similar point in #503 but mentioned a different folder. I don't know which of you is correct, and the person responsible for the HiGHS build system is currently busy writing up her PhD. I'll assign it to her to address when she "emerges" after Christmas. Otherwise, you can clearly make a local change to src/CMakeLists.txt
