### ISSUE TITLE
Tagged versions

### ISSUE THREAD

**Issue by odow** [ERGO-Code/HiGHS#595]
I notice that you're now at v1.1:
https://github.com/ERGO-Code/HiGHS/blob/5713a7104a9038dc9386c7637e5f35b1db6ed957/CMakeLists.txt#L7

Does that mean you're going to start following semantic versioning with releases?

If so, it's very helpful if you can tag a GitHub release for each version: 
 * https://github.com/ERGO-Code/HiGHS/releases
 * https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases

Once you have a GitHub release tagged, we can build the HiGHS binaries off that release. 

It also makes things like the Mittelmann benchmarks using "HiGHS v1.1.1" more explicit as to exactly which version was used.

**Comment by jajhall** [comment]
v1.1.1 is now tagged as current release!

**Comment by DillonJ** [comment]
For what it's worth as per https://github.com/ERGO-Code/HiGHS/issues/660 I'd be very interested in a new tagged release of HiGHS so I can access new features through HiGHS.jl

**Comment by jajhall** [comment]
@DillonJ Thanks for your kind words about HiGHS. 

What's said by @mckib2 is generally correct: we try to ensure that `master` is "safe". Whilst we work on solver development and documentation, we don't want to be focusing too much on creating releases - strictly we don't consider HiGHS to be "formally" released at all since there's very limited documentation. However, a lot of useful stuff and performance enhancements have been added since v1.1.1 was created on 27 September, so we should create a new tagged release without undue delay. 

Hopefully this should be available via HiGHS.jl.  However, because HiGHS is developing so rapidly, new versions can break the Julia interface, although this has become less of a problem over time. Unfortunately, the person on the HiGHS end of the Julia interface is writing up her PhD so may not have time to fix things. This situation won't last forever, and then she'll be working full-time on HiGHS. 

So the short answer is that I can't give you a schedule for an up-to-date version of HiGHS to be available via HiGHS.jl, sorry.
