### ISSUE TITLE
example for LP warm start?

### ISSUE THREAD

**Issue by kehlert** [ERGO-Code/HiGHS#617]
Hi, I'm having trouble finding documentation on how to properly do a warm-start with the HiGHs solver. Looks like it's called "hot start" in the code, but it's not clear exactly how it should be used, especially when changing the right-hand side of the constraints. I assumed that the MIP solver would be using it, but I didn't see any references to a warm/hot start in the MIP code.

Is there an example anywhere? Is it as simple as calling get/setHotStart?

edit: after experimenting, looks like the `Highs` object (C++ interface) automatically uses warm/hot starts.

**Comment by jajhall** [comment]
There are various warm/hot start facilities in HiGHS, and I'm sorry that the documentation is lagging behind. As you suggest, HiGHS will automatically use warm/hot starts if it can, so all that a user has to do is call run() after changing a model or loading a new one. I've realised from your question that this simplicity is obscured by the existence of get/setHotStart and (un)freezeBasis. The latter methods are sophisticated levels of hot start that were written for the HiGHS MIP solver - which uses multiple instances of the HiGHS class. 

If you're just changing the RHS of constraints, (using changeRowsBounds) after a default solve (ie not using the Interior point solver) then HiGHS will recognise that the modified problem can be solved using the optimal solution (basis and basis matrix factorization, if you're familiar with these issues) of the original problem. The same is true if you change variable costs or bounds. 

The more you change an LP, the more has to be done to take advantage of its optimal solution when re-solving, but HiGHS will do all it can invisibly. There are some situations where it is better to use an optimal basis saved from solving another LP, and this can be done with get/setBasis.  

Until we've got extensive documentation - we're a very small team and the current priority is MIP solver performance - I'll see that there are a few more comments in examples like call_highs_from_cpp.cpp.

Thanks for your patience and I hope that, otherwise, HiGHS is proving to be satisfactory!

**Comment by jajhall** [comment]
Comments added to Highs.h, indicating (un)freezeBasis and get/setHotStart as advanced methods: for HiGHS MIP solver

**Comment by SanPen** [comment]
Hi, I am interested in using hot-start, however after reading the comments above I am not sure how yet.

Let's suppose I have the following code:

```
Highs highs;

// 1. pass a model
highs.passModel(MY_MODEL1);

// 2. execute
HighsStatus return_status = highs.run(); 

// 3. collect the results and do some operation ...

// 4. pass a modified version of the model 1
highs.passModel(MY_MODEL1_MODIFIED); 

// 5. execute
HighsStatus return_status = highs.run(); 

// 6. collect the results and do some operation ...
```

Before the step 5, I'd expect some sort of initial solution passing. 

Does the second run get automatically hot started?

How can I hot start a model with an already feasible solution that I have? (independently of previous runs)

thanks,
Santiago

**Comment by jajhall** [comment]
If you've only got a feasible point, then set it up as a HighsSolution instance `solution` and pass it before 5. using

`highs.passSolution(solution)`

**Comment by aphi** [comment]
Is this possible via highspy at this stage? To pass a single starting feasible solution for a model to the solver.

Looking in the `highs_bindings.cpp` I don't see passSolution exposed there. There are some `starts` references but I guess they refer to indices of relevant coefficients in a matrix.

**Comment by jajhall** [comment]
I've added 'highs_passSolution' to 'highs_bindings.cpp', but it's still in the 'latest' branch, and releases are generated using 'master'. 

If you can install HiGHS 'latest' from source, then you can install highspy locally.

**Comment by aphi** [comment]
Thank you @jajhall
