### ISSUE TITLE
Unbounded/infeasible MIP

### ISSUE THREAD

**Issue by jajhall** [ERGO-Code/HiGHS#654]
Test case MIP-unbounded in TestMipSolver.cpp exposes two errors. An unbounded MIP is deemed to have an optimal solution without presolve. With presolve, highs.run() doesn't distinguish after the MIP solver returns HighsModelStatus::kUnboundedOrInfeasible. However, to do so requires the MIP solver to run (correctly) without presolve.

Code is in branch unbounded-mip

**Comment by lgottwald** [comment]
HiGHS should never try to solve a MIP without presolve when presolve determines UnboundedOrInfeasible. The option to allow unbounded or infeasible as status should only be considered for LP. When a MIP is unbounded or infeasible the algorithms used may not work properly as the LP relaxation would be unbounded and cannot be used for branch and bound. Branch and bound can only work properly when the LP solution is primal/dual optimal because it needs a primal solution to check for integer feasibility and a corresponding dual feasible solution to know that this primal solution does indeed provide a lower bound . It may work to check whether a solution can be found by setting the objective to zero but I would leave that up to the user.

An unbounded MIP is almost always a modelling error and when a user wants to rather know whether any feasible solution exists they should call the solver without objective in the first place.

I will still look into why the MIP is solved to status optimal without presolve while presolve determines kUnboundedOrInfeasible.

**Comment by jajhall** [comment]
Thanks. I'm happy to accept all his, and to feed it back to the SciPy guys, who are putting together their interface to solve MIPs.

Of course, if someone gives HiGHS an unbounded MIP and turns off presolve, HiGHS should still give a model status that's consistent, so thanks for looking at why optimality is returned in this case.

**Comment by lgottwald** [comment]
The issue was what I suspected, that the branch-and-bound does not work when the LP relaxation is unbounded. Hence the MIP solver will enumerate all nodes that are there as the LP relaxation will always return kError as status but then will proceed to warn that the LP could not be solved with all integer columns fixed and that the node has been declared infeasible. Since there search space is not bounded this will go on infinitely.

In this particular case what additionally happens is that IPM, used to determine the analytical center, will return status kOptimal as the objective is set to zero to determine the analytical center. This is used to do additional fixings since for a bounded polytope all columns that sit at their bound in the analytical center of the polytope must sit at their bound for all feasible LP solutions. For unbounded polytopes this does not seem to hold and also the analytical center is not well-defined. The fixing due to the analytic center computation leads to the wrong status of optimal as the single unbounded column is set to sit at its bound.

I added the handling for the case when the LP relaxation turns out to be unbounded and pushed it to the unbounded-mip branch. What now happens is that none of the further steps of the branch and bound or analytic center computation will happen when the first LP is unbounded. I assume that only the first LP can turn out to be unbounded because the LP will only become further restricted regarding column bounds and additional rows. If that happens I will check whether the primal solution of the unbounded LP relaxation is feasible for the MIP. If that is the case then the status will be set to unbounded, otherwise the status will be unbounded or infeasible. If there is no integer feasible solution then the status must be set to unbounded or infeasible because it is mathematically possible that an LP relaxation is unbounded and not infeasible, but contains no integer points so the MIP is infeasible.

To reliably decide the status unbounded for the MIP one needs to find a feasible solution. I think due to linearity, if an integer feasible solution exists, and the LP relaxation is unbounded, then infinitely many integer feasible solutions must exist and the MIP is therefore unbounded too. The unbounded ray could be scaled to be integral on all integer columns and then any integer multiple of it would provide a feasible solution for the MIP.

For distinguishing the status when the MIP is determined to be unbounded or infeasible, the proper approach would not be to solve without presolve, as for LP, but to solve without objective function. If the status of this zero-objective MIP is optimal then a feasible point exists and the status of the original LP is unbounded, otherwise the status would be infeasible. But solving a whole MIP without objective function is mathematically just as hard as the original MIP and I don't think HiGHS by default should spent this effort on a MIP when not explicitly requested by the user. Calling a branch-and-bound solver on a model that is unbounded does not make much sense and then converting it to a feasibility problem automatically and spending possibly long time to find a solution of arbitrary quality with regards to the original objective is likely not what the user intended. If it is important to just know whether a model is feasible then users should call HiGHS without an unbounded objective in the first place, or call HiGHS again with a zero-objective when the status is unbounded or infeasible.

Also in the branch I therefore added an exception to the check of the status when the model is a MIP so that no error is issued.

**Comment by jajhall** [comment]
> The issue was what I suspected, that the branch-and-bound does not work when the LP relaxation is unbounded. Hence the MIP solver will enumerate all nodes that are there as the LP relaxation will always return kError as status but then will proceed to warn that the LP could not be solved with all integer columns fixed and that the node has been declared infeasible. Since the search space is not bounded this will go on infinitely.

Makes sense
 
> In this particular case what additionally happens is that IPM, used to determine the analytical center, will return status kOptimal as the objective is set to zero to determine the analytical center. This is used to do additional fixings since for a bounded polytope all columns that sit at their bound in the analytical center of the polytope must sit at their bound for all feasible LP solutions. For unbounded polytopes this does not seem to hold and also the analytical center is not well-defined. The fixing due to the analytic center computation leads to the wrong status of optimal as the single unbounded column is set to sit at its bound.
> 
> I added the handling for the case when the LP relaxation turns out to be unbounded and pushed it to the unbounded-mip branch. What now happens is that none of the further steps of the branch and bound or analytic center computation will happen when the first LP is unbounded. I assume that only the first LP can turn out to be unbounded because the LP will only become further restricted regarding column bounds and additional rows. If that happens I will check whether the primal solution of the unbounded LP relaxation is feasible for the MIP. If that is the case then the status will be set to unbounded, otherwise the status will be unbounded or infeasible. If there is no integer feasible solution then the status must be set to unbounded or infeasible because it is mathematically possible that an LP relaxation is unbounded and not infeasible, but contains no integer points so the MIP is infeasible.

Indeed - as in the second test case that I constructed in MIP-unbounded
 
> To reliably decide the status unbounded for the MIP one needs to find a feasible solution. I think due to linearity, if an integer feasible solution exists, and the LP relaxation is unbounded, then infinitely many integer feasible solutions must exist and the MIP is therefore unbounded too. The unbounded ray could be scaled to be integral on all integer columns and then any integer multiple of it would provide a feasible solution for the MIP.

> For distinguishing the status when the MIP is determined to be unbounded or infeasible, the proper approach would not be to solve without presolve, as for LP, but to solve without objective function. If the status of this zero-objective MIP is optimal then a feasible point exists and the status of the original LP is unbounded, otherwise the status would be infeasible. But solving a whole MIP without objective function is mathematically just as hard as the original MIP and I don't think HiGHS by default should spent this effort on a MIP when not explicitly requested by the user. Calling a branch-and-bound solver on a model that is unbounded does not make much sense and then converting it to a feasibility problem automatically and spending possibly long time to find a solution of arbitrary quality with regards to the original objective is likely not what the user intended. If it is important to just know whether a model is feasible then users should call HiGHS without an unbounded objective in the first place, or call HiGHS again with a zero-objective when the status is unbounded or infeasible.

Makes sense. Something that we can stress in documentation
 
> Also in the branch I therefore added an exception to the check of the status when the model is a MIP so that no error is issued.

Thanks 

I've tidied up TEST_CASE("MIP-integrality", "[highs_test_mip_solver]") so that it works through all six cases. This exposed a minor bug in Highs::run() that I've fixed, so there are changes pushed to unbounded-mip
