### ISSUE TITLE
setting log callbacks

### ISSUE THREAD

**Issue by svigerske** [ERGO-Code/HiGHS#709]
It would be nice to have a method in the `Highs` class to set the log callbacks.

I currently use
```cpp
   gh->highs = new Highs();
   HighsOptions& options = const_cast<HighsOptions&>(gh->highs->getOptions());
   options.printmsgcb = gevprint;
   options.logmsgcb = gevlog;
   options.msgcb_data = (void*) gh->gev;
   highsSetLogCallback(options);
```
I know I could avoid the `const_cast` by creating an own big `HighsOptions` object, setting the callbacks there, and then passing this to HiGHS, but that seems overkill.
While there are methods in the `Highs` class to set other options, there seems nothing to set the log callbacks.

I tried just calling `highsSetLogCallback(gevprint, gevlog, (void*)gh->gev)`, but `Highs::run()` calls `highsSetLogCallback(options)`, so my callbacks were overwritten.

To me, it would make sense to completely separate the log callbacks from the options, too.    
Further, the callbacks seem to be global variable, which means that I loose thread-safety here.

**Comment by jajhall** [comment]
Enhancement of the logging is on the stack. Others have suggested that being able to recover the last ERROR log line would be helpful: indeed, it might well be helpful to developers as well as users.

The C++ in the current logging callback mechanism is beyond me, but I don't imagine that it's hard for the likes of @lgottwald.

**Comment by lgottwald** [comment]
I would add the callbak to the log options and simply move the msgbuffer into the function without static keyword. Also it should be the last local variable declared so that tht 65kb space between other local variables. Creating a local array in the function comes for free, there is no need for a global variable or to retain the space when simply able to use the stack space.

**Comment by lgottwald** [comment]
I also can do this later

**Comment by jajhall** [comment]
Thanks. I thought that `msgbuffer` was the accumulated logging output from multiple calls, in which case I thought it would have to be associated with a particular instance of `log_options_`.

**Comment by lgottwald** [comment]
Oh, ok, that I would need to double check. If you are right then it needs to be in the log_options

**Comment by jajhall** [comment]
Or, maybe I misunderstood the nature of logging callbacks. Perhaps they are called rather than using the usual printing method, so that users have control of them, so historical logging doesn't need to be recorded. But why was the buffer ever static. 

Any review of this should also incorporate the suggestion of @odow that the last error message can be recovered after returning from a HiGHS method. Something that would be useful for us, too.

**Comment by lgottwald** [comment]
That is what I would assume. They are called instead of printf so that users are able to control how output is processed.
