### ISSUE TITLE
Support -fno-rtti?

### ISSUE THREAD

**Issue by chriselrod** [ERGO-Code/HiGHS#822]
It seems this library contains just two `dynamic_cast`s, only one of which is in `src`.
I don't know the source, but I'm wondering how important these are; would it be feasible to support building without RTTI?

**Comment by jajhall** [comment]
The only `dynamic_cast` I can see (using a `grep` script) is in `src/interfaces/OsiHiGHSSolverInterface.cpp`, so isn't really part of HiGHS. Since the OSI interface doesn't work, and hasn't been worked on for three years, I don't know why the `dynamic_cast` was used, and why it was felt necessary. It's possible that it can be eliminated.

Where did you see the other `dynamic_cast`?

**Comment by lgottwald** [comment]
grep in external/ or src/ shows no other occurrence of dynamic_cast

**Comment by jajhall** [comment]
So, if you build without OSI, you can safely delete `src/interfaces/OsiHiGHSSolverInterface.cpp` (if necessary).

**Comment by chriselrod** [comment]
The other one was: https://github.com/ERGO-Code/HiGHS/blob/574d56dfd0cee73c6c738b6fd8d83d15a4984ec1/app/cxxopts.hpp#L1055-L1059
so I added `-DCXXOPTS_NO_RTTI` to the cmake flags, and deleted `src/interfaces/Osi*`.

**Comment by jajhall** [comment]
Thanks, `HiGHS\app` contains the code only used for the HiGHS executable, so isn't in the library.

**Comment by chriselrod** [comment]
Is there a cmake option to turn off building the executable?

**Comment by jajhall** [comment]
I don't think so
