### ISSUE TITLE
option "solver" on MIP

### ISSUE THREAD

**Issue by svigerske** [ERGO-Code/HiGHS#904]
If I run HiGHS on a MIP and set option "solver", it seems to solve only its continuous relaxation.
How to set the LP solver that is used for the first LP relaxation at the root node of the MIP then?

**Comment by jajhall** [comment]
In #760 the option `mip_root_lp_strategy` is created. There were some issues with using IPM, but I think that they were fixed so I'll look again at this PR.

**Comment by jannicklange** [comment]
Can you maybe add some sort of warning to the textual description for the "solver" option? I stumbled across the same issue as svigerske. Without deeper knowledge of HiGHS, this behavior is somewhat surprising to me.

Do you have an estimated date, when the next official release (that also includes #760 and the fix for #959) is planned?
Thanks in advance!

**Comment by jajhall** [comment]
Yes, I'll add some text to the README

We should be ready for a new release soon, and it will include  #760 and the fix for #959
