### ISSUE TITLE
Optimality Gap Issues when objective value is negative

### ISSUE THREAD

**Issue by kaarthiksundar** [ERGO-Code/HiGHS#943]
There seems to be a bug in computing optimality gaps when Best Bnd or Best sol is close to zero. 

See the following log 

````
       Nodes      |    B&B Tree     |            Objective Bounds              |  Dynamic Constraints |       Work      
     Proc. InQueue |  Leaves   Expl. | BestBound       BestSol              Gap |   Cuts   InLp Confl. | LpIters     Time

 R       0       0         0   0.00%   -11.32104865    5.098652075      322.04%        0      0      0      2118     0.1s
         0       0         0   0.00%   -9.324882225    5.098652075      282.89%    10407    819      0     10503     5.3s
         0       0         0   0.00%   -8.9836515      5.098652075      276.20%     9080    917      0     17911    10.4s
 L       0       0         0   0.00%   -8.980312368    2.964355575      402.94%     8612    828      0     18290    12.4s
 L       0       0         0   0.00%   -8.980312368    2.356446412      481.10%     5245    518      0     24488    14.2s
       233     232         1   0.00%   -8.844735272    2.356446412      475.34%     5247    518      0    152442    37.9s
 L     233     186         1   0.00%   -8.844735272    0.6483478562    1464.20%     7676   1014      0    156244    44.0s
       524     474         3   0.00%   -8.844735272    0.6483478562    1464.20%    11025   1025      0    205060    51.0s
       803     749         5   0.00%   -8.844735272    0.6483478562    1464.20%    10534    727      0    230904    56.1s
      1042     984         7   0.00%   -8.844735272    0.6483478562    1464.20%    11213   1059      0    254784    62.0s
      1300    1238         9   0.00%   -8.844735272    0.6483478562    1464.20%     9816   1203      0    285824    68.1s
      1567    1501        11   0.00%   -8.844735272    0.6483478562    1464.20%    10057   1009      0    325932    75.7s
 L    1567    1259        11   0.00%   -8.844735272    -0.0744302063      Large    11175   1272      0    331370    83.4s
      1800    1393        13   0.00%   -8.785796736    -0.0744302063      Large    10232    924      0    388994    90.3s
      2012    1665        31   0.00%   -8.785796736    -0.0744302063      Large    11155   1134      0    419080    97.1s
      2096    1664        32   0.00%   -8.785796736    -0.0744302063      Large    10724   1202      0    449980   104.0s
      2407    1930        58   0.00%   -8.785796736    -0.0744302063      Large     9049    647     11    483148   110.6s
      2514    2001        72   0.00%   -8.785796736    -0.0744302063      Large    10389    963     12    511190   116.1s
      2764    2292        92   0.00%   -8.759720549    -0.0744302063      Large     9774   1050     16    545062   123.6s
````

The gap should actually decrease.

**Comment by odow** [comment]
It looks like the optimality gap is defined as
```
| BestBound - BestSol |
-----------------------
     | BestSol |
```
in which case, this isn't a bug, but there might be a more useful definition that could be used.

**Comment by jajhall** [comment]
Thanks @odow The default gap is relative, since an absolute gap depends on objective magnitude. I agree that what's reported looks odd. Perhaps a denominator of `max(1,| BestSol|)` would be better. What's your view @lgottwald ?

**Comment by lgottwald** [comment]
I sticked to how gurobi defines the gap to avoid adding more confusing, see here:

https://www.gurobi.com/documentation/9.5/refman/mipgap2.html

**Comment by jajhall** [comment]
Interesting. I see the simplicity argument - and reflecting Gurobi isn't a bad idea. Does it affect termination if the optimal objective value is $z_P=0$? Once the optimal solution is found, the gap is infinite until $z_D=0$, when it is defined to be zero - so the tolerance plays no role.

**Comment by lgottwald** [comment]
Also, there is not really something that is much better. The gap definition using the primal bound magnitude makes most sense, when considering the primal bound to be the optimal solution. Then it corresponds to how approximation algorithms are treated in the literature too where performance guarantees relative to the optimal solution value are used. Before the optimal solution value is known the gap is a bit less useful, but of course the solver cannot know whether it will find a better solution, so using the primal bound corresponds to the best guess so far.

Using the `max(1,` is not a solution for making the gap non-increasing. I removed that kind of behavior because it would alter the gap when scaling the objective function which is counter intuitive for a relative measure. A model with an optimal objective below 1 can have a completely well defined gap value with the normal definition.

It does not affect termination, but of course the objective of zero will make the solver not terminate due to a relative gap. It's not really possible to guess what the user wanted. There is still the absolute gap limit that is used for this case. Also it rarely happens, because most often the models with optimal objective 0 are feasibility problems with objective coefficients all zero, so the solve stops upon discovering the first primal solution.

**Comment by kaarthiksundar** [comment]
I understand why gaps increase before decreasing. I was thinking May be you log abs gap as well.

**Comment by lgottwald** [comment]
No, in the log there is only the relative gap currently and of course the bound values. Another progress measure in the log is the estimated percentage of explored leave nodes which will reach 100% when all leave nodes, and hence all nodes of the tree are explored.

**Comment by kaarthiksundar** [comment]
Easy fix is to report both the absolute and relative gap.

**Comment by lgottwald** [comment]
Of course that's possible. I do not want to infinitely clutter the log's with more information though and the absolute gap is implicitly given by the bounds, so is not really vital information.

**Comment by jajhall** [comment]
I take @lgottwald 's point on not having 'max(1, | BestSol|). It's not worth reporting absolute gap for the few cases where it is valuable. Gurobi doesn't.

**Comment by kaarthiksundar** [comment]
Fair enough.
