### ISSUE TITLE
bitwise-instead-of-logical in HighsMipSolverData.cpp

### ISSUE THREAD

**Issue by FlorianSchwendinger** [ERGO-Code/HiGHS#945]
In `HiGHS/src/mip/HighsMipSolverData.cpp` line 586 to 587
```cpp
        numBin += ((mipsolver.model_->col_lower_[i] == 0.0) &
                   (mipsolver.model_->col_upper_[i] == 1.0));
```
I assume there is a typo and you want to do
```cpp
        numBin += ((mipsolver.model_->col_lower_[i] == 0.0) &&
                   (mipsolver.model_->col_upper_[i] == 1.0));
```
which means replacing `&` with `&&`.

You could add `enable_cxx_compiler_flag_if_supported("-Wbitwise-instead-of-logical")`
to your Makefile than starting with clang 14 this type of typos would be automatically detected.

**Comment by jajhall** [comment]
That looks like an error @lgottwald

**Comment by lgottwald** [comment]
Since this is for counting the number of times the condition is true using the bitwise operator avoids having any conditional branch whereas using the logical operator would require a branch due to short circuit evaluation. Semantically both is equivalent and correct. If there was any code to be executed for the condition being true then there would be a conditional branch in any case and I would have used the logical to begin with.

**Comment by jajhall** [comment]
Brilliant @lgottwald !

**Comment by mingodad** [comment]
Can a comment be added to that line of code to make it clear that indeed that was the intention based on @lgottwald explanation so people seeing the compiler warning can understand it and ignore ?

**Comment by jajhall** [comment]
I'll do it, because it's easy to add, but it's only a compiler warning
