### ISSUE TITLE
Documentation for feasibility tolerance parameters

### ISSUE THREAD

**Issue by stephane-caron** [ERGO-Code/HiGHS#996]
I couldn't find in the [documentation](https://ergo-code.github.io/HiGHS/) details about the termination criteria related to the primal and dual feasibility tolerance parameters. Am I correct in assuming they correspond to the primal and dual residuals? That is to say:

$$
\begin{align}
\Vert \max(L - A x, 0) \Vert_\infty & \leq \epsilon_{primal} \\
\Vert \max(A x - U, 0) \Vert_\infty & \leq \epsilon_{primal} \\
\Vert \max(l - x, 0) \Vert_\infty & \leq \epsilon_{primal} \\
\Vert \max(x - u, 0) \Vert_\infty & \leq \epsilon_{primal} \\
\Vert H x + c + A^T y + z \Vert_\infty & \leq \epsilon_{dual}
\end{align}
$$

where the $\max$ are componentwise, $y$ and $z$ the dual multipliers for row and column inequality constraints, $\epsilon_{primal/dual}$ are the primal/dual feasibility tolerance parameter. Is that indeed what HiGHS is doing?

**Context:** I'm asking this question as part of a note I'm writing on [tolerance parameters in QP solvers](https://scaron.info/blog/optimality-conditions-and-numerical-tolerances-in-qp-solvers.html). Feel free to check that the statements made there are accurate, all feedback welcome :slightly_smiling_face:

**Comment by jajhall** [comment]
Not quite. The primal feasibility tolerances are on the max of all differences between the solution values `x` and the bounds on the variables (so - as you suggest) and between the row activities `Ax` and the bounds on the constraints. This is because the inactive row activities are obtained by solving a system of equations. The values of the residuals in the solution of these systems aren't monitored, as they should be small, even for ill-conditioned problems.

**Comment by stephane-caron** [comment]
Thanks for your reply. By "row activity" do you mean the slackness of a row, *e.g.* $(A_i^T x - U)$?

If I get your point correctly, this part matches what HiGHS checks:

$$
\begin{align}
\Vert \max(l - x, 0) \Vert_\infty & \leq \epsilon_{primal} \\
\Vert \max(x - u, 0) \Vert_\infty & \leq \epsilon_{primal} \\
\Vert H x + c + A^T y + z \Vert_\infty & \leq \epsilon_{dual}
\end{align}
$$

And, if we write $\Pi_{act}$ the projector on active row inequalities at a given solver step, this is what HiGHS checks for rows:

$$
\begin{align}
\Vert \max(\Pi_{act} (L - A x), 0) \Vert_\infty & \leq \epsilon_{primal} \\
\Vert \max(\Pi_{act} (A x - U), 0) \Vert_\infty & \leq \epsilon_{primal} 
\end{align}
$$

The assumption being that on inactive constraints the values $(I - \Pi_{act})(L - Ax)$ and $(I - \Pi_{act})(A x - U)$ are largely negative, thus the max with zero will be zero and the check can be skipped (which would make intuitive sense to me).

**Comment by jajhall** [comment]
Row activity is the value of `y=Ax`. In the simplex solver values for `x` and `y` are maintained by updating and periodic solution of `Bx_B=-Nx_N`, where values of  `x` and `y` are partitioned between the vectors `x_B` and `x_N`. Thus `y` isn't obtained by computing `Ax`.  However, I'm talking about the simplex (and MIP) solvers, and you're looking down at the QP solver level, in which I'm not so clear how the tolerances are interpreted. @feldmeier is the person to give you this answer. However, he's not currently working on HiGHS, so he may well not respond quickly.

**Comment by michaels0m** [comment]
Hi, has there been any progress on this? 

I was looking at comparing various solvers and I came across your blog post @stephane-caron (it was super helpful and explained the concepts clearly, so thank you for publishing it).

Understanding the termination criteria used by HiGHS would be super useful when it comes to comparing it with other solvers. I would be happy to help with the documentation but would require some help finding the criteria.

**Comment by jajhall** [comment]
No progress yet, but @feldmeier will soon be back as an active member of the HiGHS team!

**Comment by feldmeier** [comment]
Working through the tolerances one at a time. 
Primal feasibility: a primal feasible solution is found by using Highs itself as phase1. At the moment HiGHS default Options are being used in this sub-instance of HiGHS, though it would make sense to pass down the Options of the main instance. Depending on the outcome of phase1, infeasibility could be declared. 
If no, no further checks are done in the QP code. Primal feasibility is maintained rather than achieved (in contrast to IPM or ADMM based solvers). 
Experience tells me that instances have to be very odd for primal violations to be larger than 10E-10.
So changing the primal feasibility tolerance setting doesn't have any effect on QPs at the moment.
